version: '3.8'

services:

  mysql:
    image: mysql:5.7
    container_name: mysql-server
    environment:
      MYSQL_ROOT_PASSWORD: 123456   # <-- 你填这个
      MYSQL_DATABASE: tododb             # <-- 你填这个
    ports:
      - "33066:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d
    networks:
      - spring-todo-net

  nacos:
    image: nacos/nacos-server:v1.4.7
    container_name: nacos-server
    environment:
      MODE: standalone
    ports:
      - "8848:8848"
    networks:
      - spring-todo-net

  gateway:
    image: todo-gateway:latest            # <-- 如果你 build 时用了别的名字，请改
    container_name: todo-gateway
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-server:3306/tododb?useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123456
      SPRING_CLOUD_NACOS_DISCOVERY_SERVER_ADDR: nacos-server:8848
    depends_on:
      - mysql
      - nacos
    networks:
      - spring-todo-net

  user-service:
    image: todo-userservice:latest        # <-- 改成你 build 的名字
    container_name: todo-user-service
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-server:3306/tododb?useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123456
      SPRING_CLOUD_NACOS_DISCOVERY_SERVER_ADDR: nacos-server:8848
    depends_on:
      - mysql
      - nacos
    networks:
      - spring-todo-net

  page-service:
    image: todo-pageservice:latest        # <-- 改成你 build 的名字
    container_name: todo-page-service
    ports:
      - "8083:8083"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-server:3306/tododb?useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123456
      SPRING_CLOUD_NACOS_DISCOVERY_SERVER_ADDR: nacos-server:8848
    depends_on:
      - mysql
      - nacos
    networks:
      - spring-todo-net

  list-service:
    image: todo-listservice:latest        # <-- 改成你 build 的名字
    container_name: todo-list-service
    ports:
      - "8084:8084"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-server:3306/tododb?useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123456
      SPRING_CLOUD_NACOS_DISCOVERY_SERVER_ADDR: nacos-server:8848
    depends_on:
      - mysql
      - nacos
    networks:
      - spring-todo-net

volumes:
  mysql_data:

networks:
  spring-todo-net:
    driver: bridge