server:
  port: 8085

jwt:
  token:
    token-expiration: 120
    token-sign-key: yydwjj

spring:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/tododb?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&tinyInt1isBit=false&allowMultiQueries=true&serverTimezone=GMT%2B8&rewriteBatchedStatements=true
    username: root
    password: 123456
  application:
    name: Common
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848