apiVersion: apps/v1
kind: Deployment
metadata:
  name: list-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: list-service
  template:
    metadata:
      labels:
        app: list-service
    spec:
      containers:
        - name: list-service
          image: yydwjj/todo-listservice
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://mysql:3306/tododb?useSSL=false&serverTimezone=UTC"
            - name: SPRING_DATASOURCE_USERNAME
              value: "root"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "123456"
            - name: SPRING_CLOUD_NACOS_DISCOVERY_SERVER_ADDR
              value: "nacos:8848"
          ports:
            - containerPort: 8084

---
apiVersion: v1
kind: Service
metadata:
  name: list-service
spec:
  selector:
    app: list-service
  ports:
    - protocol: TCP
      port: 8084
      targetPort: 8084